### ISSUE TITLE
enumeration type definition has become disconnected

### ISSUE THREAD

**Issue by justiceb** [illuminated-g/lv-oopanel#2]
![image](https://user-images.githubusercontent.com/7429922/217707131-fb8f9144-e62a-4b69-953e-32902765eb9a.png)

I've tested this in LV 2021 SP1 32 and 64 bit.

I've seen this before, I think it's an annoying LabVIEW bug.  I've fixed this in the past by renaming the type definion within the user event and then recompiling.

**Comment by justiceb** [comment]
Same issue exists for the Close UE "reason" typedef

**Comment by negentropicdev** [comment]
Perhaps a funky masscompile issue, let me check this out on a machine I didn't develop this on and see if it's reproducing for me.

**Comment by negentropicdev** [comment]
Confirmed. Hooray for LabVIEW not breaking with examples that have the event but don't break until trying to use the data. I'll hit up the linker info and see what LV thinks it has and try and track down where it lost it.

**Comment by justiceb** [comment]
Cool, Glad to hear it's not just my computer then.  I've seen this issue before, I'd be curious to know how exactly you solve it to relink things properly.  I'd definitely put this in the "LV bug" category

**Comment by negentropicdev** [comment]
Definitely not the same category as issue 3 ;)

**Comment by justiceb** [comment]
haha, issue #3 is a silly inconsequential mistake.  This one is a bit more workflow breaking.
Cool code, I'm gonna use it for something.  We'll see if I'm allowed to open-source what I use it for!

**Comment by negentropicdev** [comment]
Found it. I must have moved it at some point and LV failed to type prop... but not break the internal code using it,
![image](https://user-images.githubusercontent.com/59840835/217712466-057c71b8-93fb-4e6a-8351-ea754d40bbf1.png)

**Comment by negentropicdev** [comment]
You see the virtual user group presentation I did on it with G Systems?

**Comment by negentropicdev** [comment]
https://www.youtube.com/live/vHBlU43eIow?feature=share&t=1475 if you haven't seen the Good Company video game production chain calculator

**Comment by negentropicdev** [comment]
Definitely curious what you'll be doing with it!

**Comment by negentropicdev** [comment]
Hmmmm. It's fine on the property VI itself, I think this might be the issue Darren presented about in his ludicrous fixes to LV bit.
![image](https://user-images.githubusercontent.com/59840835/217714635-ff8369d1-8588-4e57-8b72-3a1021b16866.png)

**Comment by justiceb** [comment]
That's how I found this. 

I emailed Jim Kring asking if he had ever seen anyone try to create dynamic splitters through the use of recursively nested subpanels with splitters inside of them.  He said that he had tried it once, and promptly crashed LabVIEW lmao.  But as a consolation prize, he directed me to that Gcon video.  Total coincidence that we keep running into each other.

I hadn't seen the video game yet.  Will check that out.

I open-sourced the Blue Origin plots with permission, but I wanted to make a multi-plot wrapper VIP package for those which would allow a user to quickly create and rearrange multiple plots on a single window with subpanels.  Ideally, whatever layout the user would want.  And then save/load the entire layout.

This code checks alot of cool boxes:
- Running shutdown/cleanup on a panel will wait for the panel to signal that it has shutdown.  This improves certainty that code isn't left running in an orphaned state
- There is a built in mechanism where you can init stuff on a panel before signaling back up to the framework that the panel has entered a running state.  This let's you open the FP in a hidden state, register control references for dynamic events, and then signal that the panel is running to the framework
- Built-in signalling for visibility of the panel.  A must-have
- OOP makes it easy to have different flavors of panels, but use the same framework

**Comment by justiceb** [comment]
Darren's content is always the best content on the forums.  Love that guy

**Comment by negentropicdev** [comment]
Dear github, just because a commit message says close doesn't mean I want the ticket closed...

Building VIP and testing an install from that. Will be updated on VIPM shortly after and I'll close the ticket then.

**Comment by negentropicdev** [comment]
0.2.0.24 should be available on VIPM now. Of course I forgot that I hadn't pushed after the last publish so version numbers were a little out of whack, let me know if you have any issues with it now.

I had to recreate the event in the Panel Events.ctl typedef to get it to link correctly everywhere. Actually I replaced it with a boolean event to keep the element and force type prop and then I re-replaced it with the Close Reason enum again.

**Comment by negentropicdev** [comment]
If you haven't seen it, make sure you check out the BD template snippet that's in the palettes for more quickly creating panel VIs

**Comment by justiceb** [comment]
I saw that!  I always feel weirded out burying an event structure in a case structure though.  (I'm looking at you JKI state machine)

**Comment by negentropicdev** [comment]
Yeah... reviewed a task today with Spencer on a library I was updating and on opening the BD the first thing that came out of his mouth was "why".

At least mine is meant purely for linear progression and doesn't bounce between events and "do things". It's an entire event loop in the case structure not an event in a case of a case structure, mine is stickier ;)

**Comment by justiceb** [comment]
yeah, your top level case stucture could be replaced by a stacked sequence structure.  it's just a linear stack.  Easy to understand, makes the code more horizontally compact.  I get it and don't mind it. 


you do you :)

**Comment by justiceb** [comment]
Issue still exists on latest VIPM package.  womp

**Comment by justiceb** [comment]
This is confirmed resolved in the latest build.  Woot
