### ISSUE TITLE
Request: Panel Manager and Panels should have different class wire appearance

### ISSUE THREAD

**Issue by justiceb** [illuminated-g/lv-oopanel#4]
These 2 classes frequently appear on the same BD and on the same API calls.  Not a huge deal, but it seems like it would improve readability quite a bit by making them different appearance:

![image](https://user-images.githubusercontent.com/7429922/217882568-6126c77d-7c81-4d0c-b3cf-0c5b22b6bcb9.png)

![image](https://user-images.githubusercontent.com/7429922/217882595-ab2ed47d-3206-4b26-8f16-89f5284351fb.png)

**Comment by negentropicdev** [comment]
Agreed, I'll make a pass at coloring and class control icon fixing up this evening.

**Comment by negentropicdev** [comment]
Going with this wire style and color scheme for default differentiation 
![image](https://user-images.githubusercontent.com/59840835/218026365-b3d47181-3810-479d-930e-8b5e5f9432e6.png)
