### ISSUE TITLE
Missing functionality in API: mechanism to Set State to "Hidden"

### ISSUE THREAD

**Issue by justiceb** [illuminated-g/lv-oopanel#6]
It's fairly common to build out applications that have nested subpanels.
In fact, I'm trying to build out a tool that uses nested panel managers.
(I have a Panel.vlclass who's Panel.vi contains subpanels that are controlled by another panel manager.)

In this example, when the top-level Panel.lvclass is hidden because it is removed from the top-level subpanel, then I need to be able to communicate to the nested, low-level Panels that they are no longer visible.  (I guess I could remove the low-level panel classes from their subpanels to propagate this communication, but that feels a bit silly.)

There are a couple of options here, but the simplest one is likely to have an API method for telling a Panel Manager class if it is visible or hidden.

**Comment by negentropicdev** [comment]
What do you think about a mechanism of a panel being able to register with the parent panel class a subpanel as a nested panel container along with the manager that manages that subpanel? Then it could automatically be forwarded to whatever is in the subpanel.

**Comment by negentropicdev** [comment]
Nvm I think you're right. What if there is no nested panel and you still want to tell a managed panel that it is hidden because a UI is hidden. I'll just add an API for telling a manager to tell a panel contained by a subpanel that it is hidden or visible. Basically just telling a manager whether a subpanel is hidden or not and it'll take care of the rest. This would also work nicely for other use-cases such as subpanels in specific tabs and all sorts of other fun stuff.

**Comment by justiceb** [comment]
On mobile.

But bingo, subpanel in tab is a way better example for this issue, exactly, you get it

**Comment by negentropicdev** [comment]
Have added API for subpanel visibility. It's also "sticky" and is remembered regardless of whether a panel is inserted or not and across panel inserts while a subpanel is hidden. Created a new Tabbed SubPanel example to demonstrate, iteration will still only count while a panel is in the visible tab or popped out to a standalone window.
![image](https://user-images.githubusercontent.com/59840835/218021094-5c1c6f5e-9b9f-494f-82e4-671aeb38006b.png)

**Comment by justiceb** [comment]
That's perfect,  good demo too

**Comment by negentropicdev** [comment]
Check out https://github.com/illuminated-g/lv-oopanel/releases/tag/0.2.0.25 and give it a shot. If you're still having issues related to #2, try uninstalling the package, clearing cache, reinstalling, and checking if any child classes you've created relink properly.

**Comment by negentropicdev** [comment]
I'll publish to VIPM once we get past the linking issues. I'll close this ticket if you're happy with the API and don't find any issues with it. If there are still issues with #2 we'll continue the convo over there.

**Comment by justiceb** [comment]
![image](https://user-images.githubusercontent.com/7429922/218135342-ce4b3161-0d51-4a98-a81e-5d55d9ba2800.png)

I think this might be an unintentionally missing error wire?

**Comment by justiceb** [comment]
This new feature is looking good, but it might still be a bit buggy?
With the new Tabbed Subpanels demo, do the following:

- Click G-A
- Switch to Page 2
- Click G-B

This produces an error.  I suspect that this might be perceived as undesired behavior.

![image](https://user-images.githubusercontent.com/7429922/218136291-5e0b2805-6442-4004-8b0c-2d3a64dc9393.png)

Unfortunately, the code assumes that if a panel state is not == "Subpanel", then it's not currently inserted into a subpanel.  This assumption is no longer valid if we are allowing for a VI to hold the state "Hidden" while still inserted in a subpanel on the hidden tab page.

**Comment by justiceb** [comment]
Good news!
I received approval to open-source the package that I've been working on.
I can't push this package to VIPM.io until lv-oopanel release 0.2.0.25 is released to VIPM though since I use the new visibility method discussed here.
(I still think that there is a bug, as described above, but this bug fortunately does not affect my use-case.)

If you want to check it out, I've uploaded things to my github.  You'd need both of the following:
https://github.com/justiceb/BluePlot/releases/tag/V1.4.5.12
https://github.com/justiceb/BluePlotMulti/releases/tag/V1.0.0.1

I don't do anything terribly fancy with panels, but this does atleast show off nested panel managers which is kinda cool.

**Comment by negentropicdev** [comment]
I'm adding a new case, "Hidden Subpanel" to capture the different behavior instead of just tracking visibility. Doesn't dilute the previous "Hidden" usage... just trying to find all the hidey holes where it is used. It'll be bumped to 0.2.0.26 when I'm ready to publish.

**Comment by justiceb** [comment]
I like that strategy, that works well

**Comment by negentropicdev** [comment]
@justiceb 0.2.0.26 is live on VIPM

**Comment by justiceb** [comment]
MultiBluePlot is also now live on VIPM, and declares 0.2.0.26 as a dependency.

Thanks a bunch!
I have no major development work remaining on the MultiBluePlot library at this moment.  I'll support it for anyone in the community that makes feature requests, but for now, I'm pretty happy with it.  This oopanel library made the panel management and communication of visibility very easy.

This panel library is very cool, I'll continue to use it for projects in the future.  So, I'll let you know if I ever run into any other bugs.

Cheers!

**Comment by negentropicdev** [comment]
Donezo
